#!/bin/bash

apikey=4f3a98b538594bd8a58f162fb4cce2b5
host=localhost:8989
sleep=600
blacklist=true

while :; do
    curl -s -X POST "$host/api/command?apikey=$apikey" -d "{\"name\":\"RssSync\"}"
    sleep $sleep
done